import type { Animation, TextStyle } from './types';

export interface TextPreset {
  id: string;
  name: string;
  /** Sample text shown in the picker. */
  sample: string;
  style: Partial<TextStyle>;
  animation?: Partial<Animation>;
}

/** One-tap text looks. Sizes assume a 1080 px tall canvas and are scaled to the project. */
export const TEXT_PRESETS: TextPreset[] = [
  {
    id: 'title',
    name: 'Title',
    sample: 'Title',
    style: { font: 'Poppins', weight: 800, size: 110, color: '#ffffff', shadow: true },
    animation: { in: 'pop', out: 'fade' },
  },
  {
    id: 'subtitle',
    name: 'Subtitle',
    sample: 'Subtitle',
    style: { font: 'Inter', weight: 600, size: 58, color: '#ffffff', shadow: true, shadowBlur: 0.2 },
    animation: { in: 'fade', out: 'fade' },
  },
  {
    id: 'caption',
    name: 'Caption',
    sample: 'Caption',
    style: {
      font: 'Inter',
      weight: 700,
      size: 54,
      color: '#ffffff',
      shadow: false,
      box: true,
      boxColor: '#000000b3',
      boxPadding: 0.35,
      boxRadius: 0.3,
    },
    animation: { in: 'fade', out: 'fade' },
  },
  {
    id: 'meme',
    name: 'Meme',
    sample: 'MEME TEXT',
    style: {
      font: 'Anton',
      weight: 400,
      size: 120,
      color: '#ffffff',
      uppercase: true,
      strokeWidth: 0.09,
      strokeColor: '#000000',
      shadow: false,
      letterSpacing: 0.02,
    },
  },
  {
    id: 'bold-pop',
    name: 'Bold pop',
    sample: 'WOW!',
    style: {
      font: 'Montserrat',
      weight: 900,
      size: 120,
      color: '#ffe14d',
      uppercase: true,
      strokeWidth: 0.08,
      strokeColor: '#1b1b1b',
      shadow: true,
      shadowColor: '#000000aa',
      shadowOffset: 0.08,
      shadowBlur: 0.02,
    },
    animation: { in: 'pop', loop: 'pulse' },
  },
  {
    id: 'neon',
    name: 'Neon',
    sample: 'Neon',
    style: {
      font: 'Pacifico',
      weight: 400,
      size: 110,
      color: '#fff4ff',
      shadow: true,
      shadowColor: '#ff3df2',
      shadowBlur: 0.35,
      shadowOffset: 0,
    },
    animation: { in: 'fade', loop: 'blink' },
  },
  {
    id: 'cinema',
    name: 'Movie',
    sample: 'THE JOURNEY',
    style: {
      font: 'Bebas Neue',
      weight: 400,
      size: 140,
      color: '#ffffff',
      letterSpacing: 0.25,
      shadow: true,
      shadowBlur: 0.25,
      shadowColor: '#000000cc',
      shadowOffset: 0,
    },
    animation: { in: 'blur', out: 'fade', inDuration: 1, outDuration: 1 },
  },
  {
    id: 'elegant',
    name: 'Elegant',
    sample: 'Elegant',
    style: { font: 'Playfair Display', weight: 700, italic: true, size: 100, color: '#ffffff' },
    animation: { in: 'fade', out: 'fade', inDuration: 0.8 },
  },
  {
    id: 'wedding',
    name: 'Wedding',
    sample: 'Forever',
    style: { font: 'Dancing Script', weight: 700, size: 120, color: '#fff6e8', shadowColor: '#00000066' },
    animation: { in: 'fade', inDuration: 1.2, out: 'fade', outDuration: 1 },
  },
  {
    id: 'handwritten',
    name: 'Note',
    sample: 'note to self',
    style: { font: 'Caveat', weight: 700, size: 100, color: '#ffffff' },
    animation: { in: 'typewriter', inDuration: 1.2 },
  },
  {
    id: 'marker',
    name: 'Marker',
    sample: 'Look!',
    style: {
      font: 'Permanent Marker',
      weight: 400,
      size: 100,
      color: '#ff5b5b',
      shadow: false,
      strokeWidth: 0.05,
      strokeColor: '#ffffff',
    },
    animation: { in: 'pop' },
  },
  {
    id: 'comic',
    name: 'Comic',
    sample: 'BOOM!',
    style: {
      font: 'Bangers',
      weight: 400,
      size: 130,
      color: '#ffd400',
      strokeWidth: 0.07,
      strokeColor: '#d7263d',
      letterSpacing: 0.04,
      shadow: true,
      shadowColor: '#000000',
      shadowOffset: 0.07,
      shadowBlur: 0,
    },
    animation: { in: 'drop', loop: 'wiggle' },
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    sample: 'Once upon a time…',
    style: { font: 'Space Mono', weight: 400, size: 60, color: '#ffffff', shadow: true },
    animation: { in: 'typewriter', inDuration: 1.6 },
  },
  {
    id: 'label',
    name: 'Label',
    sample: 'NEW',
    style: {
      font: 'Poppins',
      weight: 800,
      size: 56,
      color: '#ffffff',
      uppercase: true,
      letterSpacing: 0.08,
      shadow: false,
      box: true,
      boxColor: '#7c5cff',
      boxPadding: 0.45,
      boxRadius: 0.5,
    },
    animation: { in: 'pop', out: 'pop' },
  },
  {
    id: 'kids',
    name: 'Playful',
    sample: 'Hooray!',
    style: {
      font: 'Fredoka',
      weight: 600,
      size: 110,
      color: '#ffffff',
      strokeWidth: 0.1,
      strokeColor: '#ff7a00',
      shadow: false,
    },
    animation: { in: 'drop', loop: 'float' },
  },
  {
    id: 'retro',
    name: 'Retro',
    sample: 'Retro',
    style: {
      font: 'Lobster',
      weight: 400,
      size: 120,
      color: '#ffcc33',
      shadow: true,
      shadowColor: '#e5446d',
      shadowBlur: 0,
      shadowOffset: 0.06,
    },
    animation: { in: 'slide-up' },
  },
];

export function textPresetById(id: string): TextPreset | undefined {
  return TEXT_PRESETS.find((p) => p.id === id);
}
